[[ -f ~/.bash_init/secret ]] && . ~/.bash_init/secret
[[ -f ~/.bash_init/homebrew ]] && . ~/.bash_init/homebrew
[[ -f ~/.bash_init/prompt ]] && . ~/.bash_init/prompt
[[ -f ~/.bash_init/aliases ]] && . ~/.bash_init/aliases
[[ -f ~/.bash_init/node ]] && . ~/.bash_init/node
[[ -f ~/.bash_init/python ]] && . ~/.bash_init/python
[[ -f ~/.bash_init/custom ]] && . ~/.bash_init/custom
[[ -f ~/.bash_init/ruby ]] && . ~/.bash_init/ruby
[[ -f ~/.bash_init/completion ]] && . ~/.bash_init/completion
